# Attempts to build ECOS in Python 2 and Python 3 on Windows
#
# https://packaging.python.org/guides/supporting-windows-using-appveyor/
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # initialize the submodule
  - git submodule update --init --recursive

  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # install needed dependencies, and pre-install numpy, scipy
  - "%PYTHON%\\python.exe -m pip install wheel numpy scipy"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  - ".\\appveyor\\build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - ".\\appveyor\\build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: 'dist\*'

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
